version: '3.8'

services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
    environment:
      - NEXUS_CONTEXT=/
      - JAVA_MAX_MEM=1200m
      - JAVA_MIN_MEM=1200m
    restart: unless-stopped

volumes:
  nexus-data:
    driver: local
